### ISSUE TITLE
Update cards database to Danse Macabre extension

### ISSUE THREAD

**Issue by franciscojunior** [franciscojunior/Vampidroid#2]
As asked by @GiottoVerducci in https://github.com/franciscojunior/Vampidroid/pull/1#issuecomment-52464758 we should update our cards database.

**Comment by franciscojunior** [comment]
After trying second option, I changed my mind and think updating the main database is easier to be done than I first thought. We simply remove all crypt and library data and copy the new data. This is easier than migrate the user data to another database and use two separated databases.

**Comment by GiottoVerducci** [comment]
Great! What tool do you use to import the data ?

**Comment by franciscojunior** [comment]
I used sqlite3 and created a script to import the data from csv files automatically. You can have a look at it here: https://github.com/franciscojunior/Vampidroid/blob/upgrade-vampidroid-db/vampiDroid/src/sql/createVampidroidDatabaseImportCsvs.sql

The problem is that some ids were changed in the new Unaligned expansion. So, there would be a problem when the user update the database as some favorite cards as well as decks would use the old ids. Then, I did some changes to the database to map the new ids to the old ones. To do that, I used another script which I didn't added to the project yet. I will do it tonight. 

But if you just want to load the csvs into a new Vampidroid.db database, the script above is enough. :)

**Comment by franciscojunior** [comment]
I just pushed to #8 the script I used to remap unaligned database to the currently used vampidroid database ids.
